### ISSUE TITLE
PSC component

### ISSUE THREAD

**Issue by erossini** [gusroitman/Charts_MudBlazor#1]
HI,
I can see you are using my library but the reference is on another project. Those are my links:

- [GitHub](https://github.com/erossini/BlazorChartjs)
- [Demo](https://chartjs.puresourcecode.com/)

Thank you,
Enrico

**Comment by gusroitman** [comment]
Hello Enrico!

Nice to meet you, i´ll change the links to your project.

I follow all your posts on Linkedin also, i can say I'm a fan. You have
done a great work with Blazor so thank you.

I usually write some articles on Linkedin about small projects that i make
with Blazor, any input that you can say would be much appreciated since i
started about a year ago so pretty new still to the technology but i want
to learn more and become an expert like you.

https://www.linkedin.com/in/gusroitman/

Best Regards,
Gustavo Roitman

**Comment by erossini** [comment]
Nice to meet you too! If you want you can write some posts also on my blog [PureSourceCode](http://www.puresourcecode.com/): I have a lot of visitors 😉
